"""lessons.code stable curriculum id

Revision ID: 7edb3ae4debd
Revises: 4f16068902fa
Create Date: 2026-09-14 09:17:56.874420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7edb3ae4debd'
down_revision: Union[str, Sequence[str], None] = '4f16068902fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('code', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'lessons', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'lessons', type_='unique')
    op.drop_column('lessons', 'code')
    # ### end Alembic commands ###
