"""phase4 ai content pipeline

Revision ID: eaad312c50de
Revises: 7edb3ae4debd
Create Date: 2026-09-19 07:06:11.339480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eaad312c50de'
down_revision: Union[str, Sequence[str], None] = '7edb3ae4debd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=160), nullable=True),
    sa.Column('publisher', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('target_age_min', sa.Integer(), nullable=True),
    sa.Column('target_age_max', sa.Integer(), nullable=True),
    sa.Column('target_level_key', sa.String(length=30), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('license_type', sa.String(length=24), nullable=False),
    sa.Column('license_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('added_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("license_type IN ('self_owned','licensed','public_domain','permission_granted','unknown')", name='ck_source_license'),
    sa.CheckConstraint("status IN ('intake','processing','processed','needs_review','failed')", name='ck_source_status'),
    sa.ForeignKeyConstraint(['added_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage_note', sa.String(length=200), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()).with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('requested_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued','extracting','chunking','analyzing','mapping','generating','validating','needs_review','completed','failed')", name='ck_job_status'),
    sa.ForeignKeyConstraint(['requested_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_processing_jobs_source_id'), 'ai_processing_jobs', ['source_id'], unique=False)
    op.create_index('ix_jobs_claim', 'ai_processing_jobs', ['status'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_table('knowledge_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('skill_key', sa.String(length=40), nullable=True),
    sa.Column('topic_key', sa.String(length=60), nullable=True),
    sa.Column('target_age_min', sa.Integer(), nullable=True),
    sa.Column('target_age_max', sa.Integer(), nullable=True),
    sa.Column('target_level_key', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('ai_model', sa.String(length=80), nullable=True),
    sa.Column('claim', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('phonics_rule','reading_strategy','vocabulary','pronunciation','spelling','comprehension','memory_technique','study_technique','teaching_method','learning_principle','assessment_method','activity_idea')", name='ck_knowledge_category'),
    sa.CheckConstraint("provenance IN ('source_fact','ai_interpretation','ai_example')", name='ck_knowledge_provenance'),
    sa.CheckConstraint("status IN ('new','mapped','conflict','discarded')", name='ck_knowledge_status'),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'content_hash', name='uq_knowledge_dedup')
    )
    op.create_index(op.f('ix_knowledge_items_content_hash'), 'knowledge_items', ['content_hash'], unique=False)
    op.create_index(op.f('ix_knowledge_items_source_id'), 'knowledge_items', ['source_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('media_type', sa.String(length=80), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=300), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extraction_backend', sa.String(length=40), nullable=True),
    sa.Column('extraction_status', sa.String(length=16), nullable=False),
    sa.Column('language_detected', sa.String(length=8), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("extraction_status IN ('pending','ok','ocr_needed','failed')", name='ck_document_extraction'),
    sa.CheckConstraint("kind IN ('file','paste','url')", name='ck_document_kind'),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_source_id'), 'source_documents', ['source_id'], unique=False)
    op.create_table('ai_usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ok','error')", name='ck_usage_status'),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['ai_processing_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_logs_job_id'), 'ai_usage_logs', ['job_id'], unique=False)
    op.create_table('content_conflicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('knowledge_a_id', sa.UUID(), nullable=True),
    sa.Column('knowledge_b_id', sa.UUID(), nullable=True),
    sa.Column('recommended_action', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open','resolved','dismissed')", name='ck_conflict_status'),
    sa.ForeignKeyConstraint(['knowledge_a_id'], ['knowledge_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_b_id'], ['knowledge_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('knowledge_item_ids', postgresql.JSONB(astext_type=sa.Text()).with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_entity_type', sa.String(length=20), nullable=True),
    sa.Column('target_entity_id', sa.UUID(), nullable=True),
    sa.Column('target_code', sa.String(length=60), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()).with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ai_model', sa.String(length=80), nullable=True),
    sa.Column('edit_count', sa.Integer(), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('new_lesson','improve_lesson','new_questions','new_pattern','curriculum_gap')", name='ck_proposal_action'),
    sa.CheckConstraint("status IN ('draft','ai_reviewed','human_review','approved','rejected','published','rolled_back')", name='ck_proposal_status'),
    sa.ForeignKeyConstraint(['approved_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['ai_processing_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_proposals_source_id'), 'content_proposals', ['source_id'], unique=False)
    op.create_table('source_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('chapter_ref', sa.String(length=160), nullable=True),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()).with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('embedding_model', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'position')
    )
    op.create_index(op.f('ix_source_chunks_document_id'), 'source_chunks', ['document_id'], unique=False)
    op.create_table('content_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('edited','approved','rejected','regenerated','published','rolled_back')", name='ck_review_action'),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposal_id'], ['content_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_reviews_proposal_id'), 'content_reviews', ['proposal_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('knowledge_item_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('page_ref', sa.Integer(), nullable=True),
    sa.Column('chapter_ref', sa.String(length=160), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['source_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_knowledge_item_id'), 'knowledge_sources', ['knowledge_item_id'], unique=False)
    op.add_column('content_versions', sa.Column('origin', sa.String(length=20), nullable=False, server_default='manual'))
    op.add_column('content_versions', sa.Column('proposal_id', sa.UUID(), nullable=True))
    op.add_column('content_versions', sa.Column('change_reason', sa.Text(), nullable=True))
    op.add_column('content_versions', sa.Column('snapshot_state', sa.String(length=10), nullable=False, server_default='after'))
    op.create_foreign_key('fk_content_versions_proposal', 'content_versions', 'content_proposals', ['proposal_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_content_versions_proposal', 'content_versions', type_='foreignkey')
    op.drop_column('content_versions', 'snapshot_state')
    op.drop_column('content_versions', 'change_reason')
    op.drop_column('content_versions', 'proposal_id')
    op.drop_column('content_versions', 'origin')
    op.drop_index(op.f('ix_knowledge_sources_knowledge_item_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_content_reviews_proposal_id'), table_name='content_reviews')
    op.drop_table('content_reviews')
    op.drop_index(op.f('ix_source_chunks_document_id'), table_name='source_chunks')
    op.drop_table('source_chunks')
    op.drop_index(op.f('ix_content_proposals_source_id'), table_name='content_proposals')
    op.drop_table('content_proposals')
    op.drop_table('content_conflicts')
    op.drop_index(op.f('ix_ai_usage_logs_job_id'), table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    op.drop_index(op.f('ix_source_documents_source_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_knowledge_items_source_id'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_content_hash'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    op.drop_index('ix_jobs_claim', table_name='ai_processing_jobs', postgresql_where=sa.text("status = 'queued'"))
    op.drop_index(op.f('ix_ai_processing_jobs_source_id'), table_name='ai_processing_jobs')
    op.drop_table('ai_processing_jobs')
    op.drop_table('content_sources')
    # ### end Alembic commands ###
